version: '3'

networks:
  recraft:

services:
  redis:
    networks:
      - recraft
    image: "redis:latest"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 1G
  bungee:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: docker/bungee/Dockerfile
    image: bungee
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Tokyo
      - SERVER_NAME=bungee
      - DOCKER_HOST=tcp://host.docker.internal:2375
    networks:
      - recraft
    ports:
      - "25580:25577"
    volumes:
      - "./bungee/build/libs:/work/plugins"
    deploy:
      resources:
        limits:
          memory: 2G
  lobby:
    depends_on:
      - redis
      - bungee
    build:
      context: .
      dockerfile: docker/lobby/Dockerfile
    image: "lobby"
    environment:
      - TZ=Asia/Tokyo
      - SERVER_NAME=lobby
    networks:
      - recraft
    ports:
      - "25566:25565"
    deploy:
      resources:
        limits:
          memory: 5G
  # BungeeのDockerCreatorに詳細が書いてある｡
  zombiehero:
    # depends_on:
    #   - redis
    #   - bungee
    #   - lobby
    build:
      context: .
      dockerfile: docker/zombiehero/Dockerfile
    image: "zombiehero"
    environment:
      - TZ=Asia/Tokyo
      - SERVER_NAME=zombiehero
    networks:
      - recraft
    ports:
      - "25566:25565"
  nginx:
    depends_on:
      - bungee
    image: "nginxreverseproxy"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - recraft
    ports:
      - "25565:25565"
    deploy:
      resources:
        limits:
          memory: 2G
