version: '3'

networks:
  recraft:

services:
  redis:
    networks:
      - recraft
    image: "redis:latest"
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 1G
  bungee:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: docker/bungee/Dockerfile
    image: bungee
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Tokyo
      - SERVER_NAME=bungee
      - DOCKER_HOST=tcp://host.docker.internal:2375
    networks:
      - recraft
    ports:
      - "25580:25577"
    volumes:
      - "./bungee/build/libs:/work/plugins"
    deploy:
      resources:
        limits:
          memory: 2G
  lobby:
    depends_on:
      - redis
      - bungee
      - db
    build:
      context: .
      dockerfile: docker/lobby/Dockerfile
    image: "lobby"
    environment:
      - TZ=Asia/Tokyo
      - SERVER_NAME=lobby
    networks:
      - recraft
    ports:
      - "25566:25565"
    deploy:
      resources:
        limits:
          memory: 5G
  # BungeeのDockerCreatorに詳細が書いてある｡
  zombiehero:
    # depends_on:
    #   - redis
    #   - bungee
    #   - lobby
    build:
      context: .
      dockerfile: docker/zombiehero/Dockerfile
    image: "zombiehero"
    environment:
      - TZ=Asia/Tokyo
      - SERVER_NAME=debug
    networks:
      - recraft
    ports:
      - "25566:25565"
  nginx:
    depends_on:
      - bungee
    image: "nginxreverseproxy"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - recraft
    ports:
      - "25565:25565"
    deploy:
      resources:
        limits:
          memory: 2G
  db:
    image: mariadb:latest
    networks:
      - recraft
    restart: always
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=narikakeisgod
    volumes:
      - ./data/sql:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    deploy:
      resources:
        limits:
          memory: 2G

  phpmyadmin:
    depends_on:
      - db
    networks:
      - recraft
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=narikakeisgod
    deploy:
      resources:
        limits:
          memory: 2G