name: ZombieHero
main: click.recraft.zombiehero.ZombieHero
version: 0.0.1
api-version: 1.19
commands:
  gun:
    description: create gun
    usage: Command usage
  monster:
    description: monster
    usage: Command usage
